name: LogCleaner CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby:
          - '3.3'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Run Linter
        run: bundle exec rubocop

      - name: Run tests
        run: bundle exec rspec

      - name: Build gem
        run: gem build log_cleaner.gemspec
